# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1512b1b5588d48f7e2c1876e3359f7136789216f7752ddb631e2cf4a1bb910edd20f5139105cd24e18f6fb6105f54245cb6c0299087a14543740f5c956124f5f

test:
  secret_key_base: a6f57a9de26ce1b092a92f0a3069b4c5c5d51f7d4f68069736219709410f23e744c9e6b4c5eb889de944c11caf741aafd8ab7d5c23fbe3850d2ed43c4b32927b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
